/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package say.my.number;

import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.util.Random;
/**
 *
 * @author Saket
 */
public class game extends javax.swing.JFrame {

    /**
     * Creates new form game
     */
    public game() {
        initComponents();
    }
//    private int z;
    private int curr;

 /*   public void setZ(int z) {
        this.z = z;
    }

    public int getZ() {
        return z;
    }

    public game(int z) {
        this.z = z;
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose number(s)");

        jLabel2.setText("YOUR TURN");

        jButton3.setText("Play Again");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.curr<20)
        {
            this.curr+=1;
            jLabel1.setText("your number "+(curr));
            if(this.curr>=20)
            {
                jLabel2.setText("YOU WON");
                jButton3.setVisible(true);
            }
            else
            {

                if(((this.curr+1)%3)!=0)
                {
                    int i=3-((this.curr+1)%3);
                    this.curr+=i;
                    if(i==2)
                        jLabel2.setText("Computer chose "+(this.curr-1)+" "+(this.curr));
                    else
                        jLabel2.setText("Computer chose "+(this.curr)); 
                    if(this.curr==20)
                    {
                        jLabel1.setText("COMPUTER WON");
                        jButton3.setVisible(true);
                    }
                }
                else
                {
                    Random r=new Random();
                    int x=r.nextInt(100);
                    x=x>50?1:2;
                    this.curr+=x;
                    if(x==2)
                        jLabel2.setText("Computer chose "+(this.curr-1)+" "+(this.curr));
                    else
                        jLabel2.setText("Computer chose "+(this.curr));
                    if(this.curr==20)
                    {
                        jLabel1.setText("COMPUTER WON");
                        jButton3.setVisible(true);
                    }
                }
            }
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(this.curr<20)
        {
            this.curr+=2;
            jLabel1.setText("your number "+(this.curr-1)+" "+(this.curr));
            if(this.curr>=20)
            {
                jLabel2.setText("YOU WON");
                jButton3.setVisible(true);
            }
            else
            {
                if(((this.curr+1)%3)!=0)
                {
            
                int i=3-((this.curr+1)%3);
                this.curr+=i;
 //           jLabel2.setText("Computer chose "+(curr-1)+" "+(curr));
                if(i==2)
                    jLabel2.setText("Computer chose "+(this.curr-1)+" "+(this.curr));
                else
                    jLabel2.setText("Computer chose "+(this.curr)); 
                if(this.curr==20)
                {
                    jLabel1.setText("COMPUTER WON");
                    jButton3.setVisible(true);
                }
                }
                else
                {   
                    Random r=new Random();
                    int x=0;
                    while(x==0||x==3)
                        x=r.nextInt(3);
                    this.curr+=x;
                    if(x==2)
                        jLabel2.setText("Computer chose "+(this.curr-1)+" "+(this.curr));
                    else
                        jLabel2.setText("Computer chose "+(this.curr));
                    if(this.curr==20)
                    {
                        jLabel1.setText("COMPUTER WON");
                        jButton3.setVisible(true);
                    }
                    
                }
            }
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new pl1or2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        System.out.print(" "+this.z);
//        final game g=new game(this.z);
        /* Create and display the form */
        jButton3.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new game().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
